version: "3.8"

services:
  backend:
    build: ./backend
    container_name: my-backend
    ports:
      - "8000:8000"  # host:container
    volumes:
      - ./backend:/app  # mount code for hot-reload (optional)
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      - backend